/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { TVShowSeries } from "../types";
import { putsDBValue, getDBValue, getAllDBValues, deleteDBValue } from "./IndexedDB";

export class SeriesService {
  // Get all indexed series
  static async getAllSeries(): Promise<TVShowSeries[]> {
    return await getAllDBValues<TVShowSeries>("series");
  }

  // Get a single series by id
  static async getSeriesById(id: string): Promise<TVShowSeries | null> {
    const data = await getDBValue<TVShowSeries>("series", id);
    return data || null;
  }

  // Save or update series
  static async saveSeries(series: TVShowSeries): Promise<void> {
    await putsDBValue("series", series);
  }

  // Delete a series index
  static async removeSeries(id: string): Promise<void> {
    await deleteDBValue("series", id);
  }

  // Quick helper to group a list of channels or files into a brand new or existing Series structure
  static async createSeriesFromEpisodes(
    seriesName: string,
    seasonNumber: number,
    episodesList: Array<{ title: string; url: string; dateKey?: string }>
  ): Promise<TVShowSeries> {
    const seriesId = `series-${seriesName.toLowerCase().replace(/\s+/g, "-")}-s${seasonNumber}`;
    
    const existing = await this.getSeriesById(seriesId);
    const mergedEpisodes = existing ? [...existing.episodes] : [];

    episodesList.forEach((ep, index) => {
      const epId = `${seriesId}-ep-${Date.now()}-${index}`;
      // Prevent duplicate URLs within the same series
      if (!mergedEpisodes.some(me => me.url === ep.url)) {
        mergedEpisodes.push({
          id: epId,
          title: ep.title,
          url: ep.url,
          episodeNumber: mergedEpisodes.length + 1,
          playCount: 0,
          dateKey: ep.dateKey,
        });
      }
    });

    const newSeries: TVShowSeries = {
      id: seriesId,
      name: seriesName,
      season: seasonNumber,
      description: `Autogenerated series grouping for ${seriesName} Season ${seasonNumber}`,
      categories: ["Syndicate", "Series"],
      episodes: mergedEpisodes,
    };

    await this.saveSeries(newSeries);
    return newSeries;
  }

  // Find next episode in the series
  static async getNextEpisode(seriesId: string, currentUrl: string): Promise<{ title: string; url: string } | null> {
    const series = await this.getSeriesById(seriesId);
    if (!series) return null;

    const currentIndex = series.episodes.findIndex(ep => ep.url === currentUrl);
    if (currentIndex !== -1 && currentIndex < series.episodes.length - 1) {
      return series.episodes[currentIndex + 1];
    }
    return null;
  }

  // Find previous episode in the series
  static async getPreviousEpisode(seriesId: string, currentUrl: string): Promise<{ title: string; url: string } | null> {
    const series = await this.getSeriesById(seriesId);
    if (!series) return null;

    const currentIndex = series.episodes.findIndex(ep => ep.url === currentUrl);
    if (currentIndex > 0) {
      return series.episodes[currentIndex - 1];
    }
    return null;
  }

  // Pre-seed some default AJN show series for the user so it displays gorgeous content immediately
  static async initSampleSeries(): Promise<void> {
    const existing = await this.getAllSeries();
    if (existing.length === 0) {
      const sample1: TVShowSeries = {
        id: "series-alex-jones-main",
        name: "[PLACEHOLDER] Alex Jones Show Primetime",
        season: 2026,
        description: "The official primetime daily broadcast series of the syndicated host.",
        categories: ["News", "Alex Jones Show", "Alternative"],
        banner: "https://upload.wikimedia.org/wikipedia/commons/e/e1/Comedy_Central_logo_2018.svg",
        episodes: [
          {
            id: "ep-aj-1",
            title: "[PLACEHOLDER] AJN Syndicate Re-ignition Hour 1",
            url: "",
            episodeNumber: 1,
            dateKey: "2026-08-18",
            playCount: 0,
          },
          {
            id: "ep-aj-2",
            title: "[PLACEHOLDER] AJN Feed Backup Archive Hour 2",
            url: "",
            episodeNumber: 2,
            dateKey: "2026-08-18",
            playCount: 0,
          }
        ],
      };

      const sample2: TVShowSeries = {
        id: "series-infowars-debate",
        name: "[PLACEHOLDER] Great Debates & Special Transmissions",
        season: 1,
        description: "Historic broadcasts and live public debates.",
        categories: ["Debates", "Historic", "Talk-Radio"],
        episodes: [
          {
            id: "ep-deb-1",
            title: "[PLACEHOLDER] Global Syndication Trial Stream Alpha",
            url: "",
            episodeNumber: 1,
            playCount: 0,
          }
        ],
      };

      await this.saveSeries(sample1);
      await this.saveSeries(sample2);
      console.log("[SeriesService] Seeded default corporate show groupings");
    }
  }
}
